export const CHANGE_DISPLAY_SONG_DETAIL = 'song-detail/CHANGE_DISPLAY_SONG_DETAIL';
export const CHANGE_DISPLAY_SONG_LYRIC = 'song-detail/CHANGE_DISPLAY_SONG_LYRIC';


export const CHANGE_CURRENT_SONG_ID = 'songDetail/CHANGE_CURRENT_SONG_ID';
export const CHANGE_CURRENT_SONG_DETAIL = 'songDetail/CHANGE_CURRENT_SONG_DETAIL';
export const ADD_TO_PLAYLIST = "songDetail/ADD_TO_PLAYLIST"